### ISSUE TITLE
fix it please 

### ISSUE THREAD

**Issue by himohitj** [byte-capsule/FanCode-Hls-Fetcher#2]

**Comment by byte-capsule** [comment]
Does it not work?

**Comment by himohitj** [comment]
> Does it not work?

Idk why it was facing issue at that point of time, but its working fine now

edit: Thank you for this awesome tool 🫡

**Comment by byte-capsule** [comment]
Yeah.... 
the script is working with free account of FanCode...
That's why some streams may not work...🥴
